machines:
  - nick: machine1
    name: machine1.example.com
    box: chef/centos-7.0
    memory: 1024
    cpus: 1
    cpucap: 100
    primary: true
    natnet: 192.168.22.0/24
    boot_timeout: 300
    box_check_update: true
    box_version: ">= 0"
    graceful_halt_timeout: 60
    post_up_message: "hello!"
    autostart: true
    networks:
      - net: private_network
        type: static
        ip: 192.168.56.100
        mask: 255.255.255.0
        interface: "intnet0"
      - net: public_network
        type: dhcp
        bridge: "en0: Wi-Fi (AirPort)"
      - net: forwarded_port
        guest: 80
        host: 54321
        protocol: tcp
    authorized_keys:
      - type: file
        path: "~/.ssh/id_rsa.pub"
      - type: static
        key: "ssh-rsa fakeSSHpubKEY km@laptop"
    provision:
      - type: file
        source: "%project.host%/config.ini"
        destination: "~/config.ini"
      - type: shell
        path: "%project.host%/bootstrap.sh"
        privileged: true
        args:
          - "%project.guest%"
      - type: puppet
        manifests_path: "%project.host%"
        manifest_file: "default.pp"
        module_path: "%project.host%/modules"
    shared_folders:
      - host: ~/projects
        guest: /srv/www
        disabled: false
        create: false
        type: null
